server:
  port: 8020
jetcache:
  # ?????0?????????????????????
  statIntervalMinutes: 15
  # ???cacheName??????key??
  areaInCacheName: false
  # ??????
  local:
    default: # default??????????????cacheName
      # ????????????caffeine/linkedhashmap
      type: linkedhashmap
      keyConvertor: fastjson
  # ??????
  remote:
    default: # default??????????????cacheName
      type: redis
      # key?????n
      keyConvertor: fastjson
      broadcastChannel: projectA
      # redis?????
      valueEncoder: java
      valueDecoder: java
      # redis???
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      # redis?????
      host: test.sksys.cn
      port: 6379

